/*
 * Board ("게시판") posts come straight from the Google Form response sheet —
 * no ko.txt/en.txt files needed. Photos are added by hand as real files
 * under content/board/{any folder name starting with the event's
 * YYYY-MM-DD}/ (the Form's own file-upload answers just link to Drive,
 * which isn't reliable to hotlink). A post is matched to its photo folder
 * by comparing dates — not an exact name/slug — so the folder can be named
 * anything as long as it starts with that date. content/board/photos.json
 * (regenerated by scripts/update-board-photos.ps1) lists each folder's
 * photo filenames.
 */
(function () {
  'use strict';

  window.BOARD_RESPONSES_CSV_URL = 'https://docs.google.com/spreadsheets/d/1DFGGePNVC5mb7JQuLAZCuQLJSJCgqJdhZS1RyIXD9C0/export?format=csv';
  window.BOARD_PHOTOS_URL = 'content/board/photos.json';

  // Matched by substring rather than the exact header text, since the form
  // questions include bilingual "한국어 | English" labels (and one has a
  // multi-line description baked into the header) that are fragile to
  // retype exactly.
  var COLUMN_HINTS = {
    eventDate: 'Date of the event',
    writtenDate: 'Date of the day writing the post',
    titleKo: 'Title of the post(KOR)',
    titleEn: 'Title of the post(ENG)',
    bodyKo: 'Body of the post(KOR)',
    bodyEn: 'Body of the post(ENG)'
  };

  function parseCSV(text) {
    var rows = [], row = [], field = '', inQuotes = false;
    for (var i = 0; i < text.length; i++) {
      var c = text[i];
      if (inQuotes) {
        if (c === '"') {
          if (text[i + 1] === '"') { field += '"'; i++; } else { inQuotes = false; }
        } else {
          field += c;
        }
      } else if (c === '"') {
        inQuotes = true;
      } else if (c === ',') {
        row.push(field); field = '';
      } else if (c === '\r') {
        // skip
      } else if (c === '\n') {
        row.push(field); rows.push(row); row = []; field = '';
      } else {
        field += c;
      }
    }
    if (field.length || row.length) { row.push(field); rows.push(row); }
    return rows;
  }

  function resolveColumns(header) {
    var resolved = {};
    Object.keys(COLUMN_HINTS).forEach(function (key) {
      var hint = COLUMN_HINTS[key];
      var found = header.find(function (h) { return h.indexOf(hint) !== -1; });
      resolved[key] = found || null;
    });
    return resolved;
  }

  // Google's Date-question responses come back like "2024. 11. 29" (with
  // spaces after the dots) - try a few reasonable interpretations and fall
  // back to showing the raw text if none parse, rather than hiding the
  // date or crashing the sort.
  function parseDateFlexible(raw) {
    if (!raw) return NaN;
    var m = /^(\d{4})\s*[.\-/]\s*(\d{1,2})\s*[.\-/]\s*(\d{1,2})/.exec(raw);
    if (m) return new Date(+m[1], +m[2] - 1, +m[3]).getTime();
    var t = Date.parse(raw);
    return isNaN(t) ? NaN : t;
  }

  function pad2(n) { return String(n).padStart(2, '0'); }

  function formatDate(raw) {
    var t = parseDateFlexible(raw);
    if (isNaN(t)) return raw || '';
    var d = new Date(t);
    return d.getFullYear() + '.' + pad2(d.getMonth() + 1) + '.' + pad2(d.getDate());
  }

  // "YYYY-MM-DD" - matches the date prefix people naturally put at the
  // front of a folder name (e.g. "2024-11-27-기후변화학회"), so photo
  // folders can be found by date instead of requiring an exact slug.
  function normalizedDate(raw) {
    var t = parseDateFlexible(raw);
    if (isNaN(t)) return '';
    var d = new Date(t);
    return d.getFullYear() + '-' + pad2(d.getMonth() + 1) + '-' + pad2(d.getDate());
  }

  // Finds the content/board/ folder (a key in photos.json) whose name
  // starts with this post's event date, wherever it is in the folder name.
  function matchPhotoKey(photosMap, dateKey) {
    if (!dateKey || !photosMap) return null;
    var key = Object.keys(photosMap).find(function (k) { return k.indexOf(dateKey) === 0; });
    return key || null;
  }

  window.BoardHelpers = { formatDate: formatDate, normalizedDate: normalizedDate, matchPhotoKey: matchPhotoKey };

  window.loadBoardPosts = function () {
    return fetch(window.BOARD_RESPONSES_CSV_URL).then(function (res) {
      if (!res.ok) throw new Error('Board responses fetch failed: ' + res.status);
      return res.text();
    }).then(function (text) {
      var rows = parseCSV(text).filter(function (r) { return r.length > 1 || (r[0] || '').trim() !== ''; });
      if (!rows.length) return [];
      var header = rows[0].map(function (h) { return h.trim(); });
      var col = resolveColumns(header);

      var posts = rows.slice(1).map(function (r, idx) {
        var obj = {};
        header.forEach(function (h, i) { obj[h] = (r[i] || '').trim(); });
        var titleKo = col.titleKo ? obj[col.titleKo] : '';
        var titleEn = col.titleEn ? obj[col.titleEn] : '';
        if (!titleKo && !titleEn) return null;
        var eventDateRaw = col.eventDate ? obj[col.eventDate] : '';
        var dateKey = normalizedDate(eventDateRaw);
        return {
          id: (dateKey || 'post') + '-' + idx, // for the #board/... URL, unrelated to photo matching
          dateKey: dateKey, // used to find this post's photo folder, if any
          date: eventDateRaw,
          dateSort: parseDateFlexible(eventDateRaw),
          titleKo: titleKo,
          titleEn: titleEn,
          bodyKo: col.bodyKo ? obj[col.bodyKo] : '',
          bodyEn: col.bodyEn ? obj[col.bodyEn] : ''
        };
      }).filter(Boolean);

      posts.sort(function (a, b) {
        var ta = isNaN(a.dateSort) ? -Infinity : a.dateSort;
        var tb = isNaN(b.dateSort) ? -Infinity : b.dateSort;
        return tb - ta;
      });
      return posts;
    });
  };

  window.loadBoardPhotos = function () {
    return fetch(window.BOARD_PHOTOS_URL).then(function (res) {
      if (!res.ok) throw new Error('Board photos manifest fetch failed: ' + res.status);
      return res.json();
    }).catch(function () {
      return {}; // no photos.json yet, or nothing uploaded - fine, posts just show no photos
    });
  };
})();
